[package]
name = "math_parser"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common_macros = "0.1.1"
factorial = "0.4.0"
itertools = "0.11.0"
